### ISSUE TITLE
Can not run `pbiviz start` out of the box

### ISSUE THREAD

**Issue by skfd** [Microsoft/powerbi-visuals-sampleslicer#4]
I did `npm install`, then I ran `pbiviz start`. This gives a lot of errors mostly about jquery typings.

    error  TYPESCRIPT  /src/sampleSlicer.ts : (81,24) Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

**Comment by cirnosu** [comment]
I have the same issue. How to fix?

**Comment by MrMeison** [comment]
@cirnosu @skfd Thank you for the feedback!
This bug in `@types/jasmine-query`. This package depends `@types/jquery: *`
Please add certain version of jQuery, e.g. certain `"@types/jquery": "2.0.41"` in your `devDependencies`
Command for install: `npm i -D @types/jquery@2.0.41`
It will fix in next version of this visual.

**Comment by skfd** [comment]
Ok, it builds for me now. Thank you!
